2019-10-29 07:33:23,766 ERROR: Exception on / [GET] [in /home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/leonid/hlam/microblog/app/routes.py", line 122, in index
    return render_template("index.html", title='Главная', form=form, posts=posts.items,
NameError: name 'form' is not defined
2019-10-29 07:35:32,990 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 07:36:05,246 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 07:36:09,799 ERROR: Exception on /user/Леонид Компанченко [GET] [in /home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/leonid/hlam/microblog/app/routes.py", line 61, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/leonid/hlam/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/leonid/hlam/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/leonid/hlam/microblog/app/templates/user.html", line 24, in block "content"
    {{ form.hidden_tag() }}
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-10-29 07:37:11,129 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 07:40:21,909 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 07:41:53,203 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 07:45:38,560 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 08:01:26,092 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-29 08:09:59,016 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-30 01:20:39,260 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-30 01:25:48,740 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MiwiZXhwIjoxNTcyMzg0ODUyLjc2ODkwNzV9.qBKvwlarXm50FQ7avmzkxwso2LHkAp1oZuTIChLMi5M [GET] [in /home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/leonid/hlam/microblog/app/routes.py", line 156, in reset_password
    form = ResetPasswordForm()
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/flask_wtf/form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/wtforms/form.py", line 272, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/wtforms/form.py", line 52, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/wtforms/meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "/home/leonid/hlam/microblog/venv/lib/python3.6/site-packages/wtforms/fields/core.py", line 353, in bind
    return self.field_class(*self.args, **kw)
TypeError: __init__() got an unexpected keyword argument 'validarors'
2019-10-30 01:27:52,859 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-30 01:30:31,306 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-30 01:46:09,057 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-10-30 01:51:30,110 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-11-03 02:42:19,283 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-11-03 03:52:36,191 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
2019-11-03 03:54:12,713 INFO: Microblog startup [in /home/leonid/hlam/microblog/app/errors.py: 35]
